### ISSUE TITLE
add r-universe as social too

### ISSUE THREAD

**Issue by RMHogervorst** [RMHogervorst/blog#54]
see <https://github.com/r-universe-org/help>

```
social:
- icon: rocket
  icon_pack: fa
  link: https://rmhogervorst.r-universe.dev/
```

- add to config.toml
- check if that is enough

https://github.com/RMHogervorst/blog/blob/main/data/beautifulhugo/social.toml
